#
# JDBC properties
#
spring.datasource.url=jdbc:mysql://localhost:3306/futbolistas_directorio
spring.datasource.username=springfutbolista
spring.datasource.password=springfutbolista

server.port = 8080